name: "@risedle/ui"

on:
  push:
    branches:
      - main
    paths:
      - "packages/ui/**"
      - ".github/workflows/risedle-ui-release.yml"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¬ Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: âœ¨ Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
          cache: "npm"
      - name: ðŸ¿ï¸ Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v2
        with:
          path: node_modules
          key:
            # prettier-ignore
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: âš’ï¸  Remove prepare script
        run: npm pkg delete scripts.prepare
      - name: âš’ï¸  Remove postinstall script
        run: npm pkg delete scripts.postinstall
      - name: ðŸ± Install dependencies
        run: npm install
      - name: âš’ï¸  Build
        run: npm run build
      - name: âš’ï¸  Set access to public
        run: npm config set access public
        working-directory: ./packages/ui
      - name: ðŸš€ Publish @risedle/ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: Risedle
          GIT_AUTHOR_EMAIL: github@risedle.com
          GIT_COMMITTER_NAME: Risedle
          GIT_COMMITTER_EMAIL: github@risedle.com
        run: npx semantic-release
        working-directory: ./packages/ui
      - name: âœ… Package published
        run: echo 'âœ… @risedle/ui published' >> $GITHUB_STEP_SUMMARY
