name: "Risedle Assets"

on:
  push:
    branches:
      - main
    paths:
      - "apps/assets/**"
      - ".github/workflows/risedle-assets.yml"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment:
      name: risedle-assets
      url: https://assets.risedle.com
    steps:
      - name: ðŸ“¬ Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: âœ¨ Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18.7.0"
          cache: "npm"
      - name: ðŸ¿ï¸ Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v2
        with:
          path: node_modules
          key:
            # prettier-ignore
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: ðŸ± Install dependencies
        run: npm install
      - name: âš’ï¸  Optimize
        run: npm run optimize -w=assets
      - name: ðŸš€ Deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy -w=assets >> $GITHUB_STEP_SUMMARY
